stages:
  - build
  - test

image: youwuyou/gomoku:latest

variables:
  DEBIAN_FRONTEND: noninteractive

build_project:
  stage: build
  script:
    - ./build-run.sh "Ninja"

run_tests:
  stage: test
  script:
    - cd cmake-build-debug
    - ctest -V