stages:
  - build
  - test

image: ubuntu:20.04

variables:
  DEBIAN_FRONTEND: noninteractive

before_script:
  - apt-get update -qy
  - apt-get install -y build-essential ninja-build libwxgtk3.0-gtk3-dev

build_project:
  stage: build
  script:
    - ./build-run.sh "Ninja"
  tags:
    - shell
    - ubuntu
    - ubuntu20.04

run_tests:
  stage: test
  script:
    - cd cmake-build-debug
    - ctest -V
  tags:
    - shell
    - ubuntu
    - ubuntu20.04